version: "3.5"
services:
  api-container:
    container_name: api-container
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/app
    working_dir: /home/app
    environment:
      - DEBUG=Auth
      - NODE_ENV=${NODE_ENV}
    command: sh -c "npm install && npm run dev  ."
    # command: sh -c "npm install && nodemon -L ."
    networks:
      api_default:
  api-mysql:
    container_name: api-mysql-container
    image: mysql:5.7.42
    restart: always
    privileged: true
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_DB_HOST=${MYSQL_DB_HOST}
      - MYSQL_DB_PORT=4406
    ports:
      - "4451:3306"
    volumes:
      - sql_data:/var/lib/mysql
    networks:
      api_default:
  api-phpmyadmin:
    container_name: api-phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PMA_HOST=api-mysql
    ports:
      - "44066:80"
    networks:
      api_default:
volumes:
  sql_data:
networks:
  api_default:
    name: api_default
